name: run tests
on: [push]
jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.5.3'
    - name: Tests
      run: |
        Rscript -e 'source("tests/testthat.R")'
